modLoader="javafml"
loaderVersion="[45,)"
license="LGPL-2.1"
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/MinecraftMineralogy/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-mineralogy"
logoFile=""
credits="Cyanobacterium, SkyBlade1978, JRIwanek, FoxNekitsune, Proxy, the MMD Team, Forge, FML, and the mod authors"
authors="Cyanobacterium, SkyBlade1978, JRIwanek"

[[mods]]
modId="mineralogy"
version="${version}"
displayName="Minecraft Mineralogy"
description='''
Fills the world with real-world rocks.
'''

[[dependencies.mineralogy]]
    modId="forge"
    mandatory=true
    versionRange="[45.4.0,46)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mineralogy]]
    modId="orespawn"
    mandatory=true
    versionRange="[4.0.6,5.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mineralogy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"
