modLoader="javafml"
loaderVersion="[66,)"
license="LGPL-2.1-only"

[[mods]]
modId="mineralogyrecipeprobe"
version="1"
displayName="Mineralogy Recipe Integration Probe"

[[dependencies.mineralogyrecipeprobe]]
modId="forge"
mandatory=true
versionRange="[66.0.0,67)"
ordering="NONE"
side="BOTH"

[[dependencies.mineralogyrecipeprobe]]
modId="mineralogy"
mandatory=true
versionRange="[6.1.2.2603001]"
ordering="AFTER"
side="BOTH"
