modLoader="javafml"
loaderVersion="[65,)"
license="LGPL-2.1-only"

[[mods]]
modId="mineralogyrecipeprobe"
version="1"
displayName="Mineralogy Recipe Integration Probe"

[[dependencies.mineralogyrecipeprobe]]
modId="forge"
mandatory=true
versionRange="[65.1.0,66)"
ordering="NONE"
side="BOTH"

[[dependencies.mineralogyrecipeprobe]]
modId="mineralogy"
mandatory=true
versionRange="[6.1.2.2602001]"
ordering="AFTER"
side="BOTH"
