modLoader="javafml"
loaderVersion="[3,)"
license="LGPL-2.1-only"

[[mods]]
modId="mineralogyrecipeprobe"
version="1"
displayName="Mineralogy Recipe Integration Probe"

[[dependencies.mineralogyrecipeprobe]]
modId="neoforge"
type="required"
versionRange="[21.1.247,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.mineralogyrecipeprobe]]
modId="mineralogy"
type="required"
versionRange="[6.1.4.121012]"
ordering="AFTER"
side="BOTH"
