license="LGPL-2.1-only"

[[mods]]
modId="mineralogyrecipeprobe"
version="1"
displayName="Mineralogy Recipe Integration Probe"

[[dependencies.mineralogyrecipeprobe]]
modId="neoforge"
type="required"
versionRange="[26.2.0.45-beta,26.2.1)"
ordering="NONE"
side="BOTH"

[[dependencies.mineralogyrecipeprobe]]
modId="mineralogy"
type="required"
versionRange="[6.1.2.2602002]"
ordering="AFTER"
side="BOTH"
