modLoader="javafml"
loaderVersion="[2,)"
license="LGPL-2.1-only"

[[mods]]
modId="mineralogyrecipeprobe"
version="1"
displayName="Mineralogy Recipe Integration Probe"

[[dependencies.mineralogyrecipeprobe]]
modId="neoforge"
type="required"
versionRange="[20.6.139,20.7)"
ordering="NONE"
side="BOTH"

[[dependencies.mineralogyrecipeprobe]]
modId="mineralogy"
type="required"
versionRange="[6.1.4.120062]"
ordering="AFTER"
side="BOTH"
